# Generated by Django 4.0.4 on 2023-07-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_post_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-createdAt',)},
        ),
    ]
